import { SocialIcons } from './../components/SocialIcons';
import { MainHeader } from './../components/MainHeader';
/* eslint-disable @next/next/no-img-element */
import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import NavBar from '../components/NavBar';
import styles from '../styles/mainheader.module.scss';
import IconsComponent from 'components/IconsComponent';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<NavBar />
			<main className={styles.header_container}>
				<MainHeader />
				<SocialIcons />
				<IconsComponent />
			</main>
		</>
	);
};

export default Home;
