import { SocialIcons } from './../components/SocialIcons'
import { MainHeader } from '../components/MainHeader'
import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import NavBar from '../components/NavBar'
import styles from '../styles/mainheader.module.scss'
import IconsComponent from 'components/IconsComponent'
import BreakComponent from 'components/BreakComponent'
import ProjectsComponent from 'components/projects/ProjectsComponent'
import MessageComponent from 'components/message/MessageComponent'
import { Footer } from 'components/Footer'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.header_container}>
        <NavBar />
        <MainHeader />
        <SocialIcons />
        <BreakComponent marginTop="4rem" />
        <IconsComponent />
        <ProjectsComponent />
        <BreakComponent marginTop="2rem" />
        <MessageComponent />
        <Footer />
      </main>
    </>
  )
}

export default Home
